### ISSUE TITLE
reduce code transferring from subdomain gateway urls and other http/https to `ipfs://` and `ipns://` urls

### ISSUE THREAD

**Issue by 2color** [ipfs/service-worker-gateway#110]
@lidel I believe you added this to the list. Can you please provide more information on what you meant?

**Comment by SgtPooki** [comment]
I think the main thing here was that we pass urls directly from service worker and helia-http-gateway to verified fetch. I believe this has been available since https://github.com/ipfs/helia-verified-fetch/pull/4 or so and updated in this repo by https://github.com/ipfs-shipyard/service-worker-gateway/pull/156

see https://github.com/ipfs-shipyard/service-worker-gateway/blob/5560b5a7b178c93f9316f7d2f1d109fd91b5c10f/src/sw.ts#L439
