### ISSUE TITLE
Missing support for index.html in HAMT-subdirectory

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#19]
This is  issue about (2) on screenshot below can be reproduced by opening `/ipfs/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/wiki/`  via service worker gateway at https://bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze.ipfs.sw.sgtpooki.com/wiki/: 

![2024-02-13_17-18](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/2e63b5f2-a5d2-4237-a32e-4ce101a1abf9)

It takes a while for this error to surface, because of a separate problem described in https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/18

**Comment by SgtPooki** [comment]
This is fixed with the changes from https://github.com/ipfs/helia/pull/450. 

1. clone code from that PR, then run 
2. `rm packages/*/*.tgz`
3. then run `npm run build && cd packages/unixfs && npm pack && cd ../verified-fetch && npm i --save ../unixfs/*.tgz && npm run build && npm pack`
4. Then run `npm i --save <pathToHeliaRepo>/packages/*/*.tgz`
5. then `npm run start`

The first request takes quite a while, but subsequent requests do not (also, my internet is really slow and borked today)


<img width="1364" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/1e581a25-aae0-4e31-941a-a49057c040d9">

<img width="1383" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/98dcf80e-6baf-406d-9f2a-98d3eef92d12">

---

These changes have been deployed to http://en-wikipedia--on--ipfs-org.ipns.sw.sgtpooki.com/

**Comment by SgtPooki** [comment]
https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/c5878a3c-2106-4e23-b1ea-cd49e45e490e
