### ISSUE TITLE
bug: fix release-please PR not running build&check workflows

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/service-worker-gateway#427]
not sure why they're not running.. build & check workflows don't run at all after waiting for days:

<img width="935" alt="image" src="https://github.com/user-attachments/assets/f7f59f0b-e8a4-4d34-a8f2-608ef5cea48f">

above taken from https://github.com/ipfs/service-worker-gateway/pull/410

**Comment by 2color** [comment]
I also noticed this with #436.

**Comment by 2color** [comment]
I suspect that this is happening due to a combination of two reasons:
- Merging to main causes the the [`release-please` job](https://github.com/ipfs/service-worker-gateway/blob/1c4b284a1e3434d01845cc20238fdb204836914f/.github/workflows/main.yml/#L167-L177) to run.
- The release-please job creates the release PR
- The release PR gets the required checks from the [CI workflow](https://github.com/ipfs/service-worker-gateway/blob/1c4b284a1e3434d01845cc20238fdb204836914f/.github/workflows/main.yml)
- But GitHub actions cannot trigger another GitHub action run so the required checks are still there.

## Possible fix

- [ ] Only trigger the CI workflow for non release pull requests
