### ISSUE TITLE
Rename and move to ipfs/ org

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#80]
ipfs-shipyard org at github will be sunsetting later this year,
I propose moving to https://github.com/ipfs/service-worker-gateway

- [x] move to ipfs/ org
- [x] rename?
- [x]  ~update `UCI_GITHUB_TOKEN` introduced in https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/117 after we finish move to `ipfs/`~
  - ~:thought_balloon:  we may want to switch to a bot one rather than using my PAT, so it does not look like I did PR: https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/120~
  - no longer relevant since #244 
- [x] create new cloudflare pages project
- [x] reattach domains 
- [x] github mgmt cleanup following tips from https://github.com/ipfs/github-mgmt/pull/58#issuecomment-1248317854
- [ ] add developer docs 
- [ ] make git push to confirm #244 works for both staging and production

cc @aschmahmann  @SgtPooki @2color @achingbrain  :+1:  / :-1:  ?

**Comment by SgtPooki** [comment]
Absolutely. Would it make sense to live at ipshipyard/service-worker-gateway?

**Comment by achingbrain** [comment]
Probably just a typo - I would have though it'd be https://github.com/ipfs/helia-service-worker-gateway ?

**Comment by achingbrain** [comment]
Ah, you mean the org `ipshipyard` vs `ipfs`.  I was talking about the repo name - this is `helia-service-worker-gateway`, the link in the OP is `service-worker-gateway`

**Comment by lidel** [comment]
It is a good opportunity to agree on both :-) 

See https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/31#issuecomment-1973271288 – suggestion is to remove `helia` from the name, because it is two projects removed from actual Helia, build on top of it, not part of it. We will still mention Helia and verified-fetch on [the landing page](https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/58) as one of the building blocks tho.

With that in mind, my suggestion is to go with simple and self-explanatory `ipfs/service-worker-gateway` (https://github.com/ipfs/service-worker-gateway).

If we want a made-up name, we could  call it `inbrowser` or some acronym  like `ipfs-swgw`. 
My renaming fatigue kicks in, so better ideas welcome.

**Comment by SgtPooki** [comment]
I think using Helia in the name would help with visibility of the underlying tech, but also tightly couples us to the Helia impl, pros and cons both ways. (PR for Helia)

as far as `ipfs` or `ipshipyard` org.. I think it may be offtopic, but related, to discuss what projects belong in ipshipyard instead of general ipfs. If we officially owning the `ipfs` org, maybe it makes sense there, but if not.. we're missing out on PR opportunities for IP Shipyard.

**Comment by 2color** [comment]
I think that like normal IPFS gateways, consumers of the SW gateway are not necessarily going to be interested in the underlying tech (especially if it works well) which is why I think it's ok to remove Helia from the repo name. We absolutely should mention it on the gateway landing page with a link to the repo, but I don't think it's necessary for the repo name.

**Comment by SgtPooki** [comment]
I can get behind that thinking

**Comment by lidel** [comment]
PSA: I will be moving to `ipfs/` later today, and switching Cloudflare Pages introduced in #247  to  the new repo. There may be a short disruption, but after it is done, we should have both repo and domains setup stable enough so it can be used in docs, tutorials, WG calls and IPFS Camp talks.
